
CREATE SEQUENCE SQ_T_USERS_CP5
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_USERS_CP5 (
    id_user NUMBER(19) NOT NULL,
    name VARCHAR2(255 CHAR),
    email VARCHAR2(255 CHAR),
    password VARCHAR2(255 CHAR),
    role VARCHAR2(50 CHAR),
    CONSTRAINT T_USERS_CP5_PK PRIMARY KEY (id_user)
);

CREATE UNIQUE INDEX T_USERS_CP5_EMAIL_UNQ ON T_USERS_CP5 (email);